thisdir = class/Microsoft.CSharp
SUBDIRS = 
include ../../build/rules.make

LIBRARY = Microsoft.CSharp.dll

LIB_MCS_FLAGS = -r:System.Core.dll -r:Mono.CSharp.dll -r:System.Dynamic.dll

include ../../build/library.make

