thisdir = nunitlite
SUBDIRS = src nunitlite-console

include ../build/rules.make

#DISTFILES = license.rtf nunit.sln nunit_VS2005.sln nunit.snk \
	#CommonAssemblyInfo.cs

all-local install-local csproj-local test-local run-test-local run-test-ondotnet-local clean-local uninstall-local doc-update-local:

dist-local: dist-default

