thisdir = nunitlite/nunitlite-console
SUBDIRS = 
include ../../build/rules.make

PROGRAM = $(topdir)/class/lib/$(PROFILE)/nunitlite-console.exe
LOCAL_MCS_FLAGS = \
	/r:nunitlite.dll

include ../../build/executable.make
